### PR TITLE
Update ani-cli to include setsid version check

### PR DESCRIPTION
**Pull request by kd00r**
Please edit line 7, the variable setsid_version should contain the version where the -f parameter was added.

### CODE REVIEW

**Comment by JLO64** [comment]
What exactly does this do? I'm only asking since it conflicts with my PR.

**Comment by kd00r** [comment]
It checks the installed version of setsid. If the installed version is below the version specified on line 7, `setsid_version="2.36.2"` in this case, the program never adds the `-f` version to the mpv play command at line 260. If it is above, it adds the `-f`.

There is a bit of trickery going on at line 258, where `sed s/[^0-9.]//g` only returns numbers and dots from `setsid- V` to the added `verchk` bash function on the same line. The only remaining trickery is on line 6, where the `verchk` function is defined. That function, together with the `-ge` (greater than or equal compare) on line 258, compares the version string we got from `setsid -V` vs what is in the `$setsid_version` variable.

The reasoning behind me doing this is because if this would have been in place when I first installed ani-cli, it would have worked out of the box for Ubuntu 18.04 with setsid version `2.31.1`.

Please see issue: https://github.com/pystardust/ani-cli/issues/106 for the full story, it turned out we had two different issues, non-installed decoders vs too early version of setsid.

I hope this makes a bit more sense now!

**Comment by JLO64** [comment]
Thanks for the insightful write up! The things we do to watch anime...

**Comment by kd00r** [comment]
Yeah, indeed. I did not know beforehand that Ubuntu 18.04 (which I unfortunately is forced to use on that particular machine) ships with this old version of setsid. I understand it's purpose in the script, but in my case with the old version did not even spew out the log file due to mpv never starting. The error was just a few characters to the left on the same line, but it took me a good 45min to find it.

**Comment by pystardust** [comment]
setsid is only used to put `mpv` in the background as a forked process.

We could remove `setsid` by just doing 
```sh
mpv "$url" >/dev/null  2>&1 &
```
But a caveat would be closing the terminal will close mpv

**Comment by ura43** [comment]
A move from setsid to nohup is planned to better support mac users and to be closer to posix compliance.
That transition will make this PR obsolete

**Pull request closed without merging**
