### PR TITLE
fix : link parsing problems and reduce curl call for majority of animes

### LINKED ISSUE #515: Unable to view an episode
**Metadata (please complete the following information)**
Version: 1.6.7
OS: Windows 10
Shell: Git Bash 
Anime: enen-no-shouboutai-ni-no-shou

**Describe the bug**
Only this episode doesn't work the rest seem to work. Shows `Video URL not found`. Was able to replicate it on Termux.

**Steps To Reproduce**

1. Run `ani-cli`
2. Search fire force
3. Choose 4
4. Choose episode 1

**Expected behavior**
Video should play

**Screenshots (if applicable)**
image

### PR DESCRIPTION
**Pull request by RaynardGerraldo**
fix #515 #542

### CODE REVIEW

**Review by 71zenith — APPROVED** [review]

**Review by Derisis13 — CHANGES_REQUESTED** [review]
Spaces on every single line, please change them to tabs. Also according to our current style guideline, `do` should be in the same row as `for`, just like `if` and `then`. I would also consider making  the `if ! ... then` into a `||`, if that makes sense for you. Otherwise looking good!

**Comment by RaynardGerraldo** [comment]
> Spaces on every single line, please change them to tabs. Also according to our current style guideline, `do` should be in the same row as `for`, just like `if` and `then`. I would also consider making the `if ! ... then` into a `||`, if that makes sense for you. Otherwise looking good!

sorry bout that thanks for the review ,and thanks for the help @71zenith

**Comment by CoolnsX** [comment]
@71zenith can u put ```-x 16 -s 16``` in line 446.. and remove commented lines above it...

**Comment by 71zenith** [comment]
> @71zenith can u put `-x 16 -s 16` in line 446.. and remove commented lines above it...

sure, but what shall be the commit message

**Comment by 71zenith** [comment]
tell before merging, we have to squash the commits

**Review by Derisis13 — APPROVED** [review]
Very nice! 
@Zenith71 you requested a reminder to squash

**Comment by Derisis13** [comment]
Although line 159 should be part of line 158...

**Comment by RaynardGerraldo** [comment]
> Although line 159 should be part of line 158...

@Derisis13 good?

**Comment by Derisis13** [comment]
> > Although line 159 should be part of line 158...
> 
> @Derisis13 good?

Perfect

**Pull request merged**
