### PR TITLE
docs: ani cli specification

### LINKED ISSUE #870: ani-cli spec RFC
Our flagset and menusystem is in dire need of stabilization.
Earlier this week I created a spec on a whiteboard that has been verified by my comaintainers.
With this ticket I want to publish the current version and track the roadmap to a digital version and then to implementation.

This is also a request for comment from users and outside contributors

image

### PR DESCRIPTION
**Pull request by port19x**
# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [x] Documentation update

## Description

closes #870 

ani-cli architecture specification is now digital

- [x] embedd under an architecture section in CONTRIBUTING.md

### CODE REVIEW

**Comment by port19x** [comment]
v3.4 release checklist:

- [x] formalize spec
- [ ] drop `-a`
- [ ] drop `-x`
- [ ] unify `-d` and `-p` (alternatively, if technically impossible, remove `-p`)
- [ ] minimize global state (see annotated screenshot below)
- [ ] migrate to fzf-only interactive menu

**Comment by port19x** [comment]
I'll make a seperate issue for 3.4 release plans

**Comment by justchokingaround** [comment]
looks fine to me, except maybe the part where we quit if range selection is invalid, i'll think more about it later, looks mergeable already

**Review by justchokingaround — APPROVED** [review]

**Comment by port19x** [comment]
> looks fine to me, except maybe the part where we quit if range selection is invalid, i'll think more about it later, looks mergeable already

We don't, we quit if the user enters "q" during range selection. Invalid will just reenter range selection.

Do you mean the postmenu invald? In that case I believe exiting is the best move

**Pull request merged**
