### PR TITLE
Add scraping for recent anime

### PR DESCRIPTION
**Pull request by drabart**
Add scraping for recent anime on main gogoanime page and selecting from these scraped.
Also fixed slight "--dub" misalignment.

### CODE REVIEW

**Comment by Reaper176** [comment]
Working great so far. <3
ty for your work.

**Comment by drabart** [comment]
Added function to check if there are unwatched episodes of anime from history (kinda resolving Issue #86 ).
(might be a bit slow with big history)

**Comment by drabart** [comment]
After some time finally got something kinda working that will resolve episode numbers like 6.5 to some extent resolving issue #138 
To use it enter it like: '[integer episode number].5]' -> 'h[integer episode number]'

If anyone has suggestions how to implement it in better way and not rewriting entire system from integers to strings, I'll gladly listen.

**Review by ura43 — APPROVED** [review]

**Review by ura43 — CHANGES_REQUESTED** [review]
Please resolve the current conflicts

**Comment by drabart** [comment]
resolved conflicts and moved half episode note to help message

**Review by ura43 — APPROVED** [review]
Looks good, will merge soon and then update the readme to reflect the new changes

**Pull request merged**
