### PR TITLE
Update README for Windows installation

### PR DESCRIPTION
**Pull request by RaynardGerraldo**
Scoop update

### CODE REVIEW

**Review by ura43 — APPROVED** [review]
We may want to discourage -u usage

**Comment by RaynardGerraldo** [comment]
What about the updates in between releases? e.g .1.6.1

**Comment by ura43** [comment]
> What about the updates in between releases? e.g .1.6.1

As long as you can update with scopp after updating through -U, it's fine for me

**Comment by RaynardGerraldo** [comment]
> > What about the updates in between releases? e.g .1.6.1
> 
> As long as you can update with scopp after updating through -U, it's fine for me

Of course,once ani-cli is installed using scoop, using the -U flag will update that file

Scoop update will run once we upload a new release e.g 1.7

**Pull request merged**
