### PR TITLE
normal quality doesn't exist

### PR DESCRIPTION
**Pull request by CoolnsX**
@ura43 maybe this fixes your problem...

And I tried it in dash.. and it was working there fine..

### CODE REVIEW

**Comment by ura43** [comment]
No it doesn't, but I have some more debugging, thanks to bash -x. Anime was flcl-dub again.
In this case, no player opens.
The screenshot shows what happens when I try to open the url that gets curled below the "normal quality doesn't exist" in a webbrowser, I get what I screenshotted below

```
+++ get_video_quality https://sbplay2.com/d/xo8vwjg5o3zh
+++ dpage_url=https://sbplay2.com/d/xo8vwjg5o3zh
++++ curl -s https://sbplay2.com/d/xo8vwjg5o3zh
++++ sed -n -E 's/.*a href="#" onclick="download_video([^"]*)".*/\1/p'
++++ head -1
+++ video_links='('\''xo8vwjg5o3zh'\'','\''n'\'','\''1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'\'')'
++++ printf normal
++++ cut -c1
+++ m=n
++++ printf '('\''xo8vwjg5o3zh'\'','\''n'\'','\''1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'\'')'
++++ cut '-d'\''' -f2
+++ i=xo8vwjg5o3zh
++++ printf '('\''xo8vwjg5o3zh'\'','\''n'\'','\''1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'\'')'
++++ cut '-d'\''' -f6
+++ h=1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a
++++ curl -s 'https://sbplay2.com/dl?op=download_orig&id=xo8vwjg5o3zh&mode=n&hash=1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'
++++ sed -n -E 's/<a href="([^"]*.mp4)".*/\1/p'
+++ video_link=
+++ '[' -z '' ']'
+++ err 'normal quality doesn'\''t exist, falling back to normal quality'
+++ printf '\033[1;31m%s\033[0m\n' 'normal quality doesn'\''t exist, falling back to normal quality'
normal quality doesn't exist, falling back to normal quality
++++ curl -s 'https://sbplay2.com/dl?op=download_orig&id=xo8vwjg5o3zh&mode=n&hash=1855550-138-100-1641464346-9b605927c6cd9bf68993db795d9bd98a'
++++ sed -n -E 's/<a href="([^"]*.mp4)".*/\1/p'
+++ video_link=
+++ printf %s ''
++ video_url=
++ printf %s ''
+ video_url=
+ referer_link=https://sbplay2.com
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 0 ']'
+ sed -E '
			s/^flcl-dub\t[0-9]+/flcl-dub\t4/
		' /home/ura/.cache/ani-hsts
+ printf '%s\n' ''

+ kill 4501
+ case $player_fn in
+ PID=4635
+ printf '\033[1;32m\nVideo playing'

Video playing+ mv /home/ura/.cache/ani-hsts.new /home/ura/.cache/ani-hsts
+ nohup mpv --http-header-fields=Referer:https://sbplay2.com ''
```
Error

**Comment by ura43** [comment]
URLs that start with https://sbplay2.com/ are never direct download links. those always start with https://www and then two digits i.e. https://www91

**Comment by CoolnsX** [comment]
it has something to do with your IP on your side... that's why some of the 50% of the time it runs and 50% it's not... 

because.. sbplay assignes the download link according to your public IP.. and if it has some problem then.. it shows this same dialogue.. I have tested it.. by changing the IP & refreshing the page... sometimes it generates the download link.. sometimes it shows the same image.. 
> Error

**Comment by CoolnsX** [comment]
my bash -x debugging with same anime and same episode

`
++ dpage_url=https://sbplay2.com/d/xo8vwjg5o3zh
++++ curl -s https://sbplay2.com/d/xo8vwjg5o3zh
++++ sed -n -E 's/.*a href="#" onclick="download_video([^"]*)".*/\1/p'
++++ head -1
+++ video_links='('\''xo8vwjg5o3zh'\'','\''n'\'','\''1855550-160-202-1641481443-c052b3a745f968bbc84d701e87c8b1e5'\'')'
++++ printf hi
++++ cut -c1
+++ m=h
++++ printf '('\''xo8vwjg5o3zh'\'','\''n'\'','\''1855550-160-202-1641481443-c052b3a745f968bbc84d701e87c8b1e5'\'')'
++++ cut '-d'\''' -f2
+++ i=xo8vwjg5o3zh
++++ printf '('\''xo8vwjg5o3zh'\'','\''n'\'','\''1855550-160-202-1641481443-c052b3a745f968bbc84d701e87c8b1e5'\'')'
++++ cut '-d'\''' -f6
+++ h=1855550-160-202-1641481443-c052b3a745f968bbc84d701e87c8b1e5
++++ curl -s 'https://sbplay2.com/dl?op=download_orig&id=xo8vwjg5o3zh&mode=h&hash=1855550-160-202-1641481443-c052b3a745f968bbc84d701e87c8b1e5'
++++ sed -n -E 's/<a href="([^"]*.mp4)".*/\1/p'
+++ video_link=
+++ '[' -z '' ']'
+++ err 'hi quality doesn'\''t exist, falling back to normal quality'
+++ printf '\033[1;31m%s\033[0m\n' 'hi quality doesn'\''t exist, falling back to normal quality'
hi quality doesn't exist, falling back to normal quality
++++ curl -s 'https://sbplay2.com/dl?op=download_orig&id=xo8vwjg5o3zh&mode=n&hash=1855550-160-202-1641481443-c052b3a745f968bbc84d701e87c8b1e5'
++++ sed -n -E 's/<a href="([^"]*.mp4)".*/\1/p'
+++ video_link=https://www91.sbcdnvideo.com/tysxeoyc2c66j6cdaa5rrv26pm33esqufl7pzjbteyi6t5lbs2556jqgrfkq/flcl-dub-episode-3.mp4
+++ printf %s https://www91.sbcdnvideo.com/tysxeoyc2c66j6cdaa5rrv26pm33esqufl7pzjbteyi6t5lbs2556jqgrfkq/flcl-dub-episode-3.mp4
++ video_url=https://www91.sbcdnvideo.com/tysxeoyc2c66j6cdaa5rrv26pm33esqufl7pzjbteyi6t5lbs2556jqgrfkq/flcl-dub-episode-3.mp4
++ printf %s https://www91.sbcdnvideo.com/tysxeoyc2c66j6cdaa5rrv26pm33esqufl7pzjbteyi6t5lbs2556jqgrfkq/flcl-dub-episode-3.mp4
+ video_url=https://www91.sbcdnvideo.com/tysxeoyc2c66j6cdaa5rrv26pm33esqufl7pzjbteyi6t5lbs2556jqgrfkq/flcl-dub-episode-3.mp4
+ referer_link=https://sbplay2.com
+ '[' 0 -eq 1 ']'
+ '[' 0 -eq 0 ']'
+ sed -E '
			s/^flcl-dub\t[0-9]+/flcl-dub\t4/
		' /home/tanveer/.cache/ani-hsts
+ printf '%s\n' https://www91.sbcdnvideo.com/tysxeoyc2c66j6cdaa5rrv26pm33esqufl7pzjbteyi6t5lbs2556jqgrfkq/flcl-dub-episode-3.mp4
https://www91.sbcdnvideo.com/tysxeoyc2c66j6cdaa5rrv26pm33esqufl7pzjbteyi6t5lbs2556jqgrfkq/flcl-dub-episode-3.mp4
+ kill 37127
+ case $player_fn in
+ PID=38085
+ printf '\033[1;32m\nVideo playing'

Video playing+ mv /home/tanveer/.cache/ani-hsts.new /home/tanveer/.cache/ani-hsts
+ nohup mpv --http-header-fields=Referer:https://sbplay2.com https://www91.sbcdnvideo.com/tysxeoyc2c66j6cdaa5rrv26pm33esqufl7pzjbteyi6t5lbs2556jqgrfkq/flcl-dub-episode-3.mp4

`

**Comment by CoolnsX** [comment]
fixed it... working again..

**Pull request merged**
