### PR TITLE
docs: add repology badge minversion

### PR DESCRIPTION
**Pull request by port19x**
# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [x] Documentation update

## Description

We need to test for the lowest point release that still works for at least some anime and use that as our minversion for the badge. 
That would clearly indicate what native packages are hard broken and differenciate them from those that are merely outdated

### CODE REVIEW

**Comment by Derisis13** [comment]
Can I push the corrections for the suse instructions to this branch?

**Comment by port19x** [comment]
> Can I push the corrections for the suse instructions to this branch?

yeah sure, the repology badge thing is very minor

**Comment by port19x** [comment]
minversion is v3.0
2.2 doesn't work anymore

**Comment by port19x** [comment]
> minversion is v3.0 2.2 doesn't work anymore

**Review by Derisis13 — APPROVED** [review]
Looks fine to me. Version bump not needed, this is only documentation update.

**Pull request merged**
