### PR TITLE
added debian instructions

### PR DESCRIPTION
**Pull request by werdahias**
# Pull Request Template

## Type of change

- [ x] Documentation update

### CODE REVIEW

**Comment by justchokingaround** [comment]
might as well just remove the whole section at this point

**Comment by werdahias** [comment]
Why?

**Comment by justchokingaround** [comment]
oh sorry, i didn't see the line with the apt command. this is actually great news. can someone test it on debian, to make sure it works?

**Comment by werdahias** [comment]
You'd need debian unstable to test it. FWIW it works fine for me

**Comment by Wiener234** [comment]
I would suggest leaving the part about uninstalling the ppa in the Readme for some time to make sure people who had the ppa remove it first before trying to install from the official servers.

**Comment by port19x** [comment]
> might as well just remove the whole section at this point

Do you mean the distro specifics in general?
That might be a discussion worth having for sure.
We're in more and more repos, links to the right places may be superior and less error prone than telling everyone what command to copy paste

**Review by nightwolf3140 — COMMENTED** [review]
`can someone test it on debian, to make sure it works?`
Changes seem great but cant confirm the package (im on arch)

**Comment by port19x** [comment]
Yeah, there is no way it doesn't work on Debian Unstable

**Review by port19x — APPROVED** [review]

**Pull request merged**
