### PR TITLE
Update ani-cli

### PR DESCRIPTION
**Pull request by ViktorMYT**
I think vlc would be better, mpv is lagging while vlc works smoothly with any video file you can imagine, while mpv will complain if you don't have proper codecs installed so I think that vlc is better in this case.

### CODE REVIEW

**Comment by pystardust** [comment]
thanks personal preference I guess, we could put that as a variable/function instead of hardcoding it maybe

**Comment by J0hsHH** [comment]
--mpv
--vlc

**Comment by Shinyzenith** [comment]
> Better alternative, use `xdg-open` this would let the user specify how to open files.

`xdg-open` could potentially call on a video player that can't render URL's? Luckily MPV does. Personally i'd prefer setting my own video player in an environment variable or as a variable in the script.

**Comment by pystardust** [comment]
the video player can be set by changing the player_fn variable in the start of the script

**Pull request closed without merging**
