### PR TITLE
Fix grep: invalid repetition count(s) regex bug

### LINKED ISSUE #418: grep: invalid repetition count(s)
**Metadata (please complete the following information):**
Version: [v1.4.0]
OS: [Mac OS Big Sur and Catalina]
Shell: [zsh and fish]

**Describe the bug**
Does not play video after episode is selected, tested with naruto, one piece, code geass...

**To Reproduce**
1. Run `ani-cli naruto`
2. Select episode 1

**Expected behavior**
Video should open. Also tested for iina with -i flag, same results.

**Screenshots (if applicable)**
Screen Shot 2022-01-26 at 5 46 30 PM

**Additional context**

### PR DESCRIPTION
**Pull request by RaynardGerraldo**
fix #418

### CODE REVIEW

**Comment by ura43** [comment]
Don't merge yourself btw

**Comment by RaynardGerraldo** [comment]
> Don't merge yourself btw

yea ill let you do it

**Review by ura43 — CHANGES_REQUESTED** [review]
Bump to v1.5.3 (someone forgot to bump to 1.5.2 earlier)

**Comment by RaynardGerraldo** [comment]
> Bump to v1.5.3 (someone forgot to bump to 1.5.2 earlier)

oh ok

**Comment by RaynardGerraldo** [comment]
bumped

**Pull request merged**
