### PR TITLE
Added in the ability to accept URLs from gogoanime as a query, as well as to run non-interactively for scripting.

### PR DESCRIPTION
**Pull request by aflyingpumpkin**
These features allow users to better interact with this utility via other bash scripts.

### CODE REVIEW

**Comment by pystardust** [comment]
Try changing the indentation to match the single tab per fold as per rest of the code to keep the commits clean

**Comment by ura43** [comment]
Conflict is easy enough to resolve

**Comment by aflyingpumpkin** [comment]
What all do I need to do to get this merged?

**Comment by ura43** [comment]
> What all do I need to do to get this merged?

Wait
And not even that long. Will probably merge today

**Comment by ura43** [comment]
Actually, I don't think you'll get this merged.
Accepting URLs bloats the code in an unacceptable way, that feature will not make it in.
Non interactiveness on the other hand is a decent feature, but without URL passing it is meaningless, as your queries get passed to the search engine and only interactively can you select your choice.
I understand that you might want to make a script that downloads a large amount of anime.
But there are dozens of gogo scrapers out there and you can probably even write your own if you truly have a usecase

**Comment by aflyingpumpkin** [comment]
I actually did write my own a while back, my use case is taking an RSS feed as an input and automatically downloading new episodes.

**Pull request closed without merging**
