### PR TITLE
Allow download without install media player

### PR DESCRIPTION
**Pull request by truboxl**
Skips checking for mpv if user is only downloading

### CODE REVIEW

**Comment by ura43** [comment]
Seems reasonable to me

**Review by ura43 — APPROVED** [review]

**Comment by ura43** [comment]
Just to clarify, does this already implement download support without a media player?

**Comment by truboxl** [comment]
Let me rebase this real quick...
Seems like somebody moved dep_ch already although not to the exact line I wanted...
https://github.com/pystardust/ani-cli/pull/172/files

I will change this PR to only include support download without media player

**Review by ura43 — CHANGES_REQUESTED** [review]
Patch doesn't allow download without mpv installed in the current state.
Maybe depchange isn't late enough yet?

**Comment by truboxl** [comment]
Hmm... weird its working fine for me.
Ok moving dep_ch further back.

**Comment by ura43** [comment]
Oh, I think I was too stupid to checkout your patch-1 branch... and used your master instead.
Feature works

**Review by ura43 — CHANGES_REQUESTED** [review]
On line 321, during the option passing, add a line `player_fn=""`
This makes the check on line 135 redundant

After that you could migrate the 3 `$is_download -eq x` tests to `-z $player_fn` tests
See [here](https://fedingo.com/how-to-check-if-variable-is-empty-or-not-in-shell-script/) if you don't know the -z test.
(tldr: `$x -eq 0` -> `-z $y`, `$x -eq 1` -> `! -z $y`)
Then remove the $is_download variable assignment on 313 and 321.

After that: congrats, you just refactored the -d handling

**Review by ura43 — APPROVED** [review]

**Comment by ura43** [comment]
Sorry, that refactor stuff is a bit more ambitious than it initially seemed. I'll merge your PR now

**Comment by truboxl** [comment]
Ah nvm, actually I thought of adding a fallback to download mode as well if mpv is detected not installed if really want to refactor the whole download use case...

**Pull request merged**
