### PR TITLE
style: consistent 4 space indentation + shfmt

### PR DESCRIPTION
**Pull request by port19x**
# Pull Request Template

## Type of change

- [X] Bug fix

## Description

I normalized indentation to 4 spaces and ran ani-cli through shfmt, which mainly fixed some case statements

## Checklist

- [X] bumped version

### CODE REVIEW

**Comment by port19x** [comment]
:skull: how does this break shellcheck this bad

**Comment by port19x** [comment]
Oh, Line 360 `<<-EOF` is incompatible with space indentation

**Review by 71zenith — APPROVED** [review]

**Comment by port19x** [comment]
Can we get rewrite the lines at 360 to not include `<<-EOF` magic?
So we can have actual consistent indentation?

**Comment by port19x** [comment]
https://google.github.io/styleguide/shellguide.html

Google thinks 2 spaces are better than 4 spaces for shell

**Comment by port19x** [comment]
Anyway, let's do 4 spaces

**Pull request merged**
