### PR TITLE
(testing linter) account for syncplay in either default location or windows path

### PR DESCRIPTION
**Pull request by port19x**
…or on the path for Windows# Pull Request Template

## Type of change

- [x] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

*ramble here*

## Checklist

- [x] any anime playing
- [x] bumped version
---
- [x] next, prev and replay work
- [x] `-c` history and continue work
- [x] `-d` downloads work
- [x] `-s` syncplay works
- [ ] `-q` quality works
- [x] `-v` vlc works
- [x] `-e` select episode works
- [x] `-S` select index works
- [x] `-r` range selection works
- [x] `--dub` and regular (sub) mode both work
- [ ] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [x] `-h` help info is up to date
- [x] Readme is up to date
- [x] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

### CODE REVIEW

**Comment by port19x** [comment]
intermediate step was necessary due to merge conflicts in #1115

**Comment by port19x** [comment]
I'll do some tests since this will be a point release.
See the checkboxes in the template

**Comment by port19x** [comment]
`-q` doesn't seem to work. Probably due to #1113

**Comment by port19x** [comment]
Aight, should be fine.
`-q` works for anime where available

**Comment by port19x** [comment]
Pinged the Tester role for this one, should probably wait for a few confirmations / a few hours just to be extra safe

**Review by justchokingaround — APPROVED** [review]

**Pull request merged**
