### PR TITLE
refactor: split long lines (and some minor stuff)

### PR DESCRIPTION
**Pull request by Derisis13**
# Refactor: split long lines (and some minor stuff)

## Type of change

- [ ] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

Long lines are a pain, and while I was at it I made some small changes

## Checklist

- [x] any anime playing
- [ ] bumped version
---
- [ ] next, prev and replay work
- [x] `-c` history and continue work
- [ ] `-d` downloads work
- [ ] `-s` syncplay works
- [ ] `-q` quality works
- [ ] `-v` vlc works
- [ ] `-e` select episode works
- [ ] `-S` select index works
- [ ] `-r` range selection works
- [ ] `--dub` and regular (sub) mode both work
- [x] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [x] `-h` help info is up to date
- [x] Readme is up to date
- [x] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

### CODE REVIEW

**Comment by Derisis13** [comment]
shfmt is (mostly) a good idea, (even though it won't let me split the long android vlc command, should I reduce that line on a roundabout way?) but I don't like that it's lumped together with shellcheck. Even version bump has its own check!

**Comment by Derisis13** [comment]
I also suggest adding the `-p` argument to the shfmt check

**Comment by Derisis13** [comment]
Original idea of splitting long lines came from @medanisjbara please credit him whoever ends up merging this

**Review by CoolnsX — APPROVED** [review]

**Comment by CoolnsX** [comment]
On termux side, since spliting is good idea, what if it doesn't launch app, that's the only concern

**Pull request closed without merging**
