### PR TITLE
wget2 info for debian package

### PR DESCRIPTION
**Pull request by Wiener234**
# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [x] Documentation update

## Description

In the Install section of the readme an info about the change of wget to wget2 for the debian package was added.
That change was made because it makes the install process easier for the user. They dont have to build wget from source.

## Checklist

- [ ] any anime playing
- [ ] bumped version
---
- [ ] next, prev and replay work
- [ ] `-c` history and continue work
- [ ] `-d` downloads work
- [ ] `-s` syncplay works
- [ ] `-q` quality works
- [ ] `-v` vlc works
- [ ] `-e` select episode works
- [ ] `-r` range selection works
- [ ] `--dub` both work
- [ ] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [ ] `-h` help info is up to date
- [x] Readme is up to date
- [ ] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

### CODE REVIEW

**Review by Derisis13 — CHANGES_REQUESTED** [review]
Way too roundabout and doesn't get the core of the message trough: the user needs to install wget2 instead of wget on debian

**Comment by Derisis13** [comment]
I think the first sentence only is enough. The wget version requirement should be stated at the dependencies section.

**Comment by Wiener234** [comment]
I changed the install section for debian and added the version to the dependencies section for wget.

**Review by Derisis13 — APPROVED** [review]
Very good, thank you

**Pull request merged**
