### PR TITLE
scraping sbplay for downloading and streaming

### PR DESCRIPTION
**Pull request by CoolnsX**
Changed the video link to sbplay.. for faster downloading and streaming

updated quality selection options..

the PR addresses.. vlc cannot open link, streaming is slow, video quality selection issues...
@ura43 please tag them here..

### CODE REVIEW

**Comment by RaynardGerraldo** [comment]
> Changed the video link to sbplay.. for faster downloading and streaming
> 
> updated quality selection options..
> 
> the PR addresses.. vlc cannot open link, streaming is slow, video quality selection issues... @ura43 please tag them here..

sorry,just tested this and for streaming it doesnt load anything, for downloading it shows this 

"Exception: [download_helper.cc:451] errorCode=1 Unrecognized URI or unsupported protocol: "

**Comment by ura43** [comment]
I'll test after lunch

**Comment by ura43** [comment]
normal quality doesn't exist, falling back to normal quality (flcl ep 1)

also worst quality doesn't exist, falling back to normal quality (one piece ep 1)

The quality stuff is still weird for sure. And it doesn't start playing with one piece ep 1

**Comment by ura43** [comment]
I can access [sbcdnvideo](http://sbcdnvideo.com/) just fine.
playing next episode is also buggy, even tho playing the initial episode worked fine with flcl alternative dub

**Review by ura43 — CHANGES_REQUESTED** [review]
Default quality should be high imo

Also more testing is needed, I'm having issues as described above

**Comment by ura43** [comment]
Default quality should be high

> Its not "worst"... Its "low" quality
> 
> Please read the quality options again

oops, you're right. New options, will check if that works.
Any idea on the normal doesn't exist falling back to normal?

**Comment by CoolnsX** [comment]
> Default quality should be high
> 
> > Its not "worst"... Its "low" quality
> > Please read the quality options again
> 
> oops, you're right. New options, will check if that works. Any idea on the normal doesn't exist falling back to normal?

oh what I did there is.. I check every episode download links in sbplay.. and normal quality is always there.. so I put it there as default..

**Comment by CoolnsX** [comment]
> normal quality doesn't exist, falling back to normal quality (flcl ep 1)
> 
> ~also worst quality doesn't exist, falling back to normal quality (one piece ep 1)~
> 
> The quality stuff is still weird for sure. And it doesn't start playing with one piece ep 1

flcl-dub??

**Comment by ura43** [comment]
> > normal quality doesn't exist, falling back to normal quality (flcl ep 1)
> > ~also worst quality doesn't exist, falling back to normal quality (one piece ep 1)~
> > The quality stuff is still weird for sure. And it doesn't start playing with one piece ep 1
> 
> flcl-dub??

yes

**Comment by CoolnsX** [comment]
> > > normal quality doesn't exist, falling back to normal quality (flcl ep 1)
> > > ~also worst quality doesn't exist, falling back to normal quality (one piece ep 1)~
> > > The quality stuff is still weird for sure. And it doesn't start playing with one piece ep 1
> > 
> > 
> > flcl-dub??
> 
> yes

its working on my side...

**Comment by CoolnsX** [comment]
https://user-images.githubusercontent.com/76195824/148231733-f89f419b-b2f4-4a80-9964-d76ff83c13c6.mp4

**Comment by CoolnsX** [comment]
> Default quality should be high imo
> 
> Also more testing is needed, I'm having issues as described above

I didn't put high option for a reason.. 
Most of the people watch old anime(e.g. - naruto) more than watching latest anime.. 
and these old anime doesn't have high quality.. so using high quality option in case of watching these anime.. will make the script defaults to normal anime again & again.. and it's annoying and time consuming.. as it again request the site for normal link...

what you can do is.. alias "ani-cli -q high" as "ani-cli"

**Comment by ura43** [comment]
Yeah, the normal quality by default does make sense if it's just not available for many anime.

https://user-images.githubusercontent.com/82055622/148235654-ed2f9b5a-7edc-4f22-8ed7-7d28dbbe2d57.mp4

**Comment by CoolnsX** [comment]
try to change in 122 line..
m=${quality:0:1}
to
m="${quality:0:1}"

**Comment by ura43** [comment]
Please pull in the latest change from master.
I think we should have shellcheck look over it

**Comment by CoolnsX** [comment]
> Please pull in the latest change from master. I think we should have shellcheck look over it

Is it working??

**Comment by ura43** [comment]
No, but I know why:
[SC3057](https://github.com/koalaman/shellcheck/wiki/SC3057) : In POSIX sh, string indexing is undefined.

**Comment by CoolnsX** [comment]
I replaced it with using cut command... I should not be a problem now..

**Comment by ura43** [comment]
> I replaced it with using cut command... I should not be a problem now.. @ura43 @RaynardGerraldo confirm please..

It's better, but I wouldn't call it fixed. Still inconsistent.
Whenever the link gets displayed it does work. But sometimes it seems to fail to parse

**Comment by CoolnsX** [comment]
> > I replaced it with using cut command... I should not be a problem now.. @ura43 @RaynardGerraldo confirm please..
> 
> It's better, but I wouldn't call it fixed. Still inconsistent. Whenever the link gets displayed it does work. But sometimes it seems to fail to parse

Can you please mention those anime in which it's not working..

**Comment by ura43** [comment]
> > > I replaced it with using cut command... I should not be a problem now.. @ura43 @RaynardGerraldo confirm please..
> > 
> > 
> > It's better, but I wouldn't call it fixed. Still inconsistent. Whenever the link gets displayed it does work. But sometimes it seems to fail to parse
> 
> Can you please mention those anime in which it's not working..

I primarily test with flcl-dub

**Comment by RaynardGerraldo** [comment]
sorry was away,testing it out now

**Comment by RaynardGerraldo** [comment]
@CoolnsX  its working but it seems to have that same cache problem ,laggging a bit but i added back the referer link with sb2play link as the value

`referer_link="https://sbplay2.com/dl?op=download_orig&id=$i&mode=$m&hash=$h"`

mpv case
`nohup "$player_fn" -http-header-fields="Referer: $referer_link" "$video_url"`

vlc case
`nohup "$player_fn" --http-referrer="$referer_link" "$video_url" `

and it somehow speeds it up

**Comment by RaynardGerraldo** [comment]
> > > > I replaced it with using cut command... I should not be a problem now.. @ura43 @RaynardGerraldo confirm please..
> > > 
> > > 
> > > It's better, but I wouldn't call it fixed. Still inconsistent. Whenever the link gets displayed it does work. But sometimes it seems to fail to parse
> > 
> > 
> > Can you please mention those anime in which it's not working..
> 
> I primarily test with flcl-dub

working with this too, all seems to be fine , i think this pr is good to go

**Comment by CoolnsX** [comment]
> @CoolnsX its working but it seems to have that same cache problem ,laggging a bit but i added back the referer link with sbplay2 link as the value
> 
> `referer_link="https://sbplay2.com/dl?op=download_orig&id=$i&mode=$m&hash=$h"`
> 
> mpv case `nohup "$player_fn" -http-header-fields="Referer: $referer_link" "$video_url"`
> 
> vlc case `nohup "$player_fn" --http-referrer="$referer_link" "$video_url" `
> 
> and it somehow speeds it up

instead of seperate referer link can you can check it by putting referer link same as video_url like
mpv case `nohup "$player_fn" -http-header-fields="Referer: $video_url" "$video_url"`

**Comment by CoolnsX** [comment]
done.. @ura43 @RaynardGerraldo confirm it..

**Comment by RaynardGerraldo** [comment]
> done.. @ura43 @RaynardGerraldo confirm it..

Currently not on my computer but you forgot the parameters

`referer_link="https://sbplay2.com/dl?op=download_orig&id=$i&mode=$m&hash=$h"`

**Comment by CoolnsX** [comment]
> > done.. @ura43 @RaynardGerraldo confirm it..
> 
> Currently not on my computer but you forgot the parameters,i dont know if this affects it or not but I'd put it in there just to make sure
> 
> `referer_link="https://sbplay2.com/dl?op=download_orig&id=$i&mode=$m&hash=$h"`

working same as without parameters... it just needs the main site link...

**Comment by RaynardGerraldo** [comment]
> > > done.. @ura43 @RaynardGerraldo confirm it..
> > 
> > 
> > Currently not on my computer but you forgot the parameters,i dont know if this affects it or not but I'd put it in there just to make sure
> > `referer_link="https://sbplay2.com/dl?op=download_orig&id=$i&mode=$m&hash=$h"`
> 
> working same as without parameters... it just needs the main site link... All is working properly.. you can check and merge it..

yep just tested it its working fine, and sorry I can't merge it , dont have write access
😅 , let @ura43 do this

**Comment by ura43** [comment]
Behaviour didn't change much for me :sweat_smile:

**Comment by ura43** [comment]
I'll merge later and we can try fixing that in another PR

**Comment by ura43** [comment]
Could also be misconfiguration on my end, as I said I just hopped distros today and I'm about to hop some more

**Comment by ura43** [comment]
Is there an anime we can use to verify quality selection?
It works for me ~50% of the time. Don't tell me it works perfectly consistent for you :sweat_smile: 
And ~50% of the time it does work I get the "normal quality doesn't exist, falling back to normal quality"

Please run the script with dash to verify

**Comment by ura43** [comment]
Lets continue this seperately, the main thing works

**Comment by CoolnsX** [comment]
> Is there an anime we can use to verify quality selection? It works for me ~50% of the time. Don't tell me it works perfectly consistent for you sweat_smile And ~50% of the time it does work I get the "normal quality doesn't exist, falling back to normal quality"
> 
> Please run the script with dash to verify

Okay I will run it on dash...

**Comment by CoolnsX** [comment]
> Is there an anime we can use to verify quality selection? It works for me ~50% of the time. Don't tell me it works perfectly consistent for you 😅 And ~50% of the time it does work I get the "normal quality doesn't exist, falling back to normal quality"
> 
> Please run the script with dash to verify

I think I found the problem as I was going through the script.. that may be fix your problem...
I will make PR for it

**Comment by qube-03** [comment]
hi,
i read all of this due to me having a similar issue where downloading and playing an episode does work, however its very very slow to cache.
i think i understand what you did to fix it, but i have no clue how to actually fix it myself, so how can i use the fix you made to hopefully resolve my problem?
thanks in advance, sorry for not being able to really add onto the discussion in any further way.

**Comment by CoolnsX** [comment]
> hi, i read all of this due to me having a similar issue where downloading and playing an episode does work, however its very very slow to cache. i think i understand what you did to fix it, but i have no clue how to actually fix it myself, so how can i use the fix you made to hopefully resolve my problem? thanks in advance, sorry for not being able to really add onto the discussion in any further way.

what you can do is to git clone again the whole repo.. and remove the previous locally stored repo ones from your computer...

**Comment by qube-03** [comment]
so this is something thats been already integrated? ill try, but if it doesnt change anything ill write another reply

**Pull request merged**
