### PR TITLE
fix: new decrypt function, script working again

### PR DESCRIPTION
**Pull request by CoolnsX**
echo is required in line 177 to create padding in new_id variable.. if someone else have a better solution can clone my repo and fix it..

### CODE REVIEW

**Comment by OrioPrisco** [comment]
doesn't seem to work ? i get the following error
```
base64: invalid input
bad decrypt
140258014115648:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../crypto/evp/evp_enc.c:599:
```
when trying to watch death note episode 1

**Comment by OrioPrisco** [comment]
after a little investigation it seems that line 180
 ``        data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | cut -d\" -f4 | tr -d '\\')``
returns the following
``<div style='color: red;font-size: 15px;text-align: center;'>Blocked by gogoplay4.com</div>``

**Comment by Derisis13** [comment]
> after a little investigation it seems that line 180 ` data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | cut -d\" -f4 | tr -d '\\')` returns the following `<div style='color: red;font-size: 15px;text-align: center;'>Blocked by gogoplay4.com</div>` Am I the only one blocked ?

Can you try it now? I applied some changes so it's dash-compatible again.

**Comment by alpha-hexor** [comment]
> after a little investigation it seems that line 180 ` data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | cut -d\" -f4 | tr -d '\\')` returns the following `<div style='color: red;font-size: 15px;text-align: center;'>Blocked by gogoplay4.com</div>` Am I the only one blocked ?

can you show me ur ajax, the ajax must be wrong that's why it's showing blocked

**Comment by alpha-hexor** [comment]
> echo is required in line 177 to create padding in new_id variable.. if someone else have a better solution can clone my repo and fix it..

Assume you want to store some data in a file and then encrypt it by openssl. The first step is u have to write the data in the binary format to get the proper result . echo -n -e is a way of doing that. I got this from this [post](https://stackoverflow.com/questions/5582778/how-to-write-a-binary-file-using-bash)

**Comment by 71zenith** [comment]
Shellcheck complains with tr. The only way i can think of bypassing it would be using sed instead of cut and tr. smth like this 
`data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | sed -e 's/{"data":"//' -e 's/"}/\n/' -e 's/\\//g')`

**Comment by CoolnsX** [comment]
> 

Can u able to push it to my fork... cause I m in clg rn

**Comment by CoolnsX** [comment]
> > 
> 
> Can u able to push it to my fork... cause I m in clg rn



> Shellcheck complains with tr. The only way i can think of bypassing it would be using sed instead of cut and tr. smth like this `data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | sed -e 's/{"data":"//' -e 's/"}/\n/' -e 's/\\//g')`

Can you able to push it on my fork??.. cause I am in clg rn..

**Comment by 71zenith** [comment]
> > > 
> > 
> > 
> > Can u able to push it to my fork... cause I m in clg rn
> 
> > Shellcheck complains with tr. The only way i can think of bypassing it would be using sed instead of cut and tr. smth like this `data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | sed -e 's/{"data":"//' -e 's/"}/\n/' -e 's/\\//g')`
> 
> Can you able to push it on my fork??.. cause I am in clg rn..

sure

**Comment by OrioPrisco** [comment]
> > after a little investigation it seems that line 180 ` data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | cut -d\" -f4 | tr -d '\\')` returns the following `<div style='color: red;font-size: 15px;text-align: center;'>Blocked by gogoplay4.com</div>` Am I the only one blocked ?
> 
> Can you try it now? I applied some changes so it's dash-compatible again.

Yes it's working now ! 



> > after a little investigation it seems that line 180 ` data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | cut -d\" -f4 | tr -d '\\')` returns the following `<div style='color: red;font-size: 15px;text-align: center;'>Blocked by gogoplay4.com</div>` Am I the only one blocked ?
> 
> can you show me ur ajax, the ajax must be wrong that's why it's showing blocked

not sure if that matters anymore, but here is what it looked like
```
1JQtDeHECjSaHawiwt/6IAWH2jT/ODwpI/Oxg9uwuZXZaGgybQbkK8j7kDSoVdY1
```
looking at the code, it seems like there is padding that might include invisible characters, not sure if those are included here.

**Review by 71zenith — APPROVED** [review]

**Review by ura43 — APPROVED** [review]

**Comment by coderaman07** [comment]
Kudos to every one who solved this bug

I have a small request from anyone of you who's free

Can anyone explain me a bit how you all are getting the video url from the website as I'm trying to rewrite the app with python for personal use ( only for streaming not to download the episode )

**Comment by 71zenith** [comment]
> Kudos to every one who solved this bug
> 
> I have a small request from anyone of you who's free
> 
> Can anyone explain me a bit how you all are getting the video url from the website as I'm trying to rewrite the app with python for personal use ( only for streaming not to download the episode )

checkout animdl https://github.com/justfoolingaround/animdl

**Comment by CoolnsX** [comment]
@alpha-hexor I have one request... if u are free then..
can you tell me the process of converting those secret keys and ivs into long numbers from given bytes..

**Pull request merged**
