### PR TITLE
fix: support using non brew iina as a player on macos

### PR DESCRIPTION
**Pull request by port19x**
# Pull Request Template

## Type of change

- [x] Bug fix

## Description

supersedes #1386 

## To test

- [x] the `-e` test works on mac os (could fail due to permissions)
- [x] both iinas work
- [x] failing dep check works as expected
- [x] test playing the next episode
- [x] test `-c`

### CODE REVIEW

**Comment by asamahy** [comment]
`play_episode()` #L258 is dependent on the case so `player_function` need to remain `iina` and then handled inside `iina` case. otherwise it gets sent into the default.

**Comment by port19x** [comment]
I see what you mean now.
*iina* should match it, will amend later

**Comment by asamahy** [comment]
`next` doesnt work. after link fetching `play_episode()` doesnt seem to get the link as far as i can tell.

**Comment by asamahy** [comment]
original ani-cli too doesnt have next working for me. dont know why. does it work on your side?

**Comment by port19x** [comment]
I'll check when I'm home on the macbook

**Comment by port19x** [comment]
I forgot :skull:, just remembered when turning on the PC at work

**Comment by port19x** [comment]
This branch works flawlessly with both iina versions.
Please open another issue for your `next` issue

**Review by 71zenith — CHANGES_REQUESTED** [review]
logically looks fine, just change echo to printf for consistency
also if u could quote the $(where_iina) , cant be too safe dealing with paths

**Comment by port19x** [comment]
>requests changes
>leaves

chad

**Pull request merged**
