### PR TITLE
New installation instructions

### PR DESCRIPTION
**Pull request by ura43**
To make the makefile obsolete

### CODE REVIEW

**Comment by sgtxd** [comment]
The new instructions should include the availability of the AUR package on Arch-based Linux distros

**Review by ThamognyaKodi — CHANGES_REQUESTED** [review]
I suggest maybe moving the period outside the link like this `The disclaimer of this project can be found [here](./disclaimer.md).` since the period is not in the link. But moreover this is a much more minute change that does not add much value to the readablity.

**Comment by ura43** [comment]
> I suggest maybe moving the period outside the link like this `The disclaimer of this project can be found [here](./disclaimer.md).` since the period is not in the link. But moreover this is a much more minute change that does not add much value to the readablity.

Good catch, I just change that back and forth whenever I need a diff to open a draft PR

**Comment by ura43** [comment]
Opening another PR soon

**Pull request closed without merging**
