### PR TITLE
Allow episode selection before select

### PR DESCRIPTION
**Pull request by grey-C47**
# Type of change

- [ ] Bug fix
- [x] Feature
- [ ] Documentation update

# Description

This commit will allow episode selection before pressing "s" by inputting a number directly.
I believe the episode selection loop could be done without entirely / merged into the main loop, but I only added this much in this commit since I don't know if you guys agree with that.

# Checklist

- [x] any anime playing
- [x] bumped version
- [x] next, prev and replay work
- [x] autoplay, aka range selection, works

# Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Not uploaded: one piece dub episode 900

### CODE REVIEW

**Comment by port19x** [comment]
This makes no sense to me. Either you know what episode you wanna watch and use the flag for that, or you continue watching with -c or you're that 1% edge case we support because we can't justify not supporting a simple 2 loc feature

**Comment by iamchokerman** [comment]
(loc = lines of code)

**Comment by grey-C47** [comment]
@port19x I'm not sure I understand what you mean. To be clear this is to select an episode after already selecting a first one. When you are given the option to play prev, next or replay. Instead of pressing (s), and then writing the episode you want. You directly write the episode's number since it doesn't conflict with 'n', 'p', 'r' or 's' (and ideally remove 's').  
  
I thought this was clearly a better design, even if it is a small thing. I thought of this because I was going through episodes of an anime trying to find one I wanted to rewatch, jumping trhough a few episodes at a time.

**Comment by port19x** [comment]
Yes, but this also circumvents explicit selection of single digit episode numbers unless I have misread.
Also explicit beats implicit.
I'd like to avoid this becoming that program where you misclick a key and get weird behaviour you didn't expect

**Pull request closed without merging**
