### PR TITLE
Consume piped input

### PR DESCRIPTION
**Pull request by rakusan2**
This is a simple answer to my question #636 
This uses the first line of whatever is piped or redirected into the script as the search parameter

I have gone with this solution as it:
- adds only a couple of lines of code
- uses what is piped in
- solves a bug
- can be easily expanded on

### CODE REVIEW

**Comment by port19x** [comment]
this feature would bump ani-cli to `2.1.0`

**Review by port19x — CHANGES_REQUESTED** [review]
- [ ] bump the version
- [ ] Don't use the `pipe` variable, directly store to query instead

**Review by port19x — APPROVED** [review]

**Comment by Derisis13** [comment]
I'm very iffy on this one: this looks like one of those side-features that are going to be first sacrifised when we feel like we're getting bloated. I think an easier solution would be to just terminate if stdin was redirected.

**Comment by rakusan2** [comment]
I find that a bit strange as piped input is fairly common on the tools I use.
Though if you do decide to sacrifice it, then it is just 4 lines of code that would be deleted and maybe a change of `elif` to `else` all of which is visible, separated, and easy to do.

**Comment by Derisis13** [comment]
> I find that a bit strange as piped input is fairly common on the tools I use. 

Piping is useful, but sometimes just doesn't make sense. You don't pipe into VIM/nano (h)top, (t)ftp (and other file-sharing programs) or package managers for example. And there's xargs if you really want this feature...

**Comment by port19x** [comment]
I fully agree that this is a less important feature at best.
The existance of xargs largely invalidates it, I didn't consider that factor.
If anything, I was hopeful that this may enable semi-automated testing through a seperate script, but that would then require many more lines to be a viable option.
After considering derisis input, I'm closing this one

**Pull request closed without merging**
