### PR TITLE
docs: prune and reorder homies

### LINKED ISSUE #1071: tv-cli link is not working
**Describe the bug**
The [tv-cli](https://github.com/Spaxly/tv-cli) link leads to a GitHub error page, all the other links are working fine.

**Screenshots (if applicable; you can just drag the image onto github)**
image

### PR DESCRIPTION
**Pull request by port19x**
# Pull Request Template

closes #1071 

## Type of change

- [ ] Bug fix
- [ ] Feature
- [X] Documentation update

### CODE REVIEW

**Review by justchokingaround — APPROVED** [review]

**Comment by Derisis13** [comment]
Since we're doing this, do we want to extract the massive list of installations/uninstallations into a separate `installing.md` that is hyperlinked in the readme?
It would be an extra step for new users, for a more streamlined readme, but we're at the point where the readme is almost as large as the whole script

**Comment by justchokingaround** [comment]
another alternative would be for use to write a proper wiki page

**Comment by port19x** [comment]
> another alternative would be for use to write a proper wiki page

I'm against using github wiki for this, since it's not version controllable

**Comment by port19x** [comment]
> Since we're doing this, do we want to extract the massive list of installations/uninstallations into a separate `installing.md` that is hyperlinked in the readme? It would be an extra step for new users, for a more streamlined readme, but we're at the point where the readme is almost as large as the whole script (373 lines and 430 lines)

I'd prefer just omitting the sections listing native packages and how to install them, especially if they appear in the repology badge.
I trust that especially linux users are capable of installing a program from their native package manager.
We don't have to tell them to `sudo apt install ani-cli`

**Comment by port19x** [comment]
Anyway I believe this should be properly discussed in another issue that I'll open

**Pull request merged**
