### PR TITLE
feat: no-detach

### LINKED ISSUE #1261: Add a --no-detach option
**Is your feature request related to a problem? Please describe.**
This is an awesome project, however there is one use case where it is currently lacking. That is allowing to do cursed things such as setting your mpv variables to:
```
vo=kitty
```
or
```
vo=sixel
```
to run everything in the terminal, or do
```
vo=gpu
gpu-context=drm
```
such as this [issue](https://github.com/pystardust/ani-cli/issues/140) suggests in order to watch anime in the tty without a display server or compositor.

The blocker for both of these issues is in the pesky `nohup` that detaches the mpv process. In the first scenario the video isn't correctly shown and in the seccond the mpv controls don't work.

**Describe the solution you'd like**
By allowing to run in `--no-detach` mode we can finally watch anime on a production server with no graphical environment.

**Describe alternatives you've considered**
I can always modify the ani-cli script in order to do this madness, since it's only a line of code.

### PR DESCRIPTION
**Pull request by port19x**
# Pull Request Template

## Type of change

- [ ] Bug fix
- [x] Feature
- [ ] Documentation update

## Description

fixes #1261 

## Checklist

- [ ] any anime playing
- [x] bumped version
---
- [x] `-h` help info is up to date
- [x] Readme is up to date
- [x] Man page is up to date

### CODE REVIEW

**Comment by germaniuss** [comment]
Awesome you're actually doing this. Locally I also removed the  `>/dev/null 2>&1 &` at the end since I believe we do not want to redirect the mpv output (nor open it in a background process). Though to be fair I am not knowledgeble enough about bash nor terminal emulators to actually know is that make a difference.

**Comment by port19x** [comment]
Can you test if it works like this as well?

**Review by CoolnsX — APPROVED** [review]

**Comment by germaniuss** [comment]
> Awesome you're actually doing this. Locally I also removed the `>/dev/null 2>&1 &` at the end since I believe we do not want to redirect the mpv output (nor open it in a background process). Though to be fair I am not knowledgeble enough about bash nor terminal emulators to actually know is that make a difference.

@port19x Sorry for getting back to you so late, had a pretty hectic week. Just tested it out, it does not seem to properly function without this (the anime is played in the background and I have to pkill mpv. I modified the sript to do `$([ "no_detach" == 0 ] && echo ">/dev/null 2>&1 &") ;;` at the end and it seems to work. Is there any technical reason not to do it?

**Comment by port19x** [comment]
> > Awesome you're actually doing this. Locally I also removed the `>/dev/null 2>&1 &` at the end since I believe we do not want to redirect the mpv output (nor open it in a background process). Though to be fair I am not knowledgeble enough about bash nor terminal emulators to actually know is that make a difference.
> 
> @port19x Sorry for getting back to you so late, had a pretty hectic week. Just tested it out, it does not seem to properly function without this (the anime is played in the background and I have to pkill mpv. I modified the sript to do `$([ "no_detach" == 0 ] && echo ">/dev/null 2>&1 &") ;;` at the end and it seems to work. Is there any technical reason not to do it?

Nah, I'll patch it

**Pull request merged**
