### PR TITLE
docs: added tabwidth specification for consistency

### PR DESCRIPTION
**Pull request by freezboltz**

### CODE REVIEW

**Review by Derisis13 — COMMENTED** [review]
I'm planning to make a formatting guideline update to `CONTRIBUTING.md` in the comming week anyway, but you make a good point.

**Comment by ura43** [comment]
Is there such a thing as tabs with different widths?

**Comment by pystardust** [comment]
nope, tabwidth is a editor property. It makes no sense associating it with the file.

**Comment by ura43** [comment]
> nope, tabwidth is a editor property. It makes no sense associating it with the file.

Thanks for confirming that. I'll close the PR

**Pull request closed without merging**
