### PR TITLE
Added flag for specifying download directory

### PR DESCRIPTION
**Pull request by HumanMan007**
As seen in some issues some people want to specify the download directory (which would be rather useful if downloads where working...) in this patch I added the ability to specify the download directory via the option -p (standing for path).
I didn't put it as the $optarg for -d as that seemed rather annoying for those that don't need it.

### CODE REVIEW

**Comment by ura43** [comment]
Seems good in theory, lets see if it eventually does

**Comment by ura43** [comment]
Conflicts are easy to resolve

**Comment by ura43** [comment]
Just noticed: its really stupid to have another flag for this when that could be an optional argument for -d

**Comment by muhi03** [comment]
Screenshot 2022-01-03 at 00 25 13


This helped for me...

**Pull request merged**
