### PR TITLE
fix: download feature

### PR DESCRIPTION
**Pull request by Dink4n**
Fixed the download feature
There is an extra dependency (ffmpeg)

### CODE REVIEW

**Comment by pystardust** [comment]
I think we need to add this to the docs @Dink4n

**Comment by ganesh314159** [comment]
@pystardust when are you going to pull his request?

**Comment by AlexFreik** [comment]
@pystardust  Do you not want to pull this request because of extra dependency?

**Comment by pystardust** [comment]
@Dink4n feel free to push directly. I may not be available due to academics.

**Pull request merged**
