### PR TITLE
fix: added progress bar while using -d 

### PR DESCRIPTION
**Pull request by r4vanan**

### CODE REVIEW

**Comment by r4vanan** [comment]
now its using python module to give process bar

**Comment by ura43** [comment]
The additional dependency might make this unappealing. At least it should be optional in some way and explicitly requested if you know what I mean

**Comment by ura43** [comment]
Could you add error handling for when the progress bar python module isn't installed / make it fall back to not using the feature if no progress bar is present?

**Review by ura43 — CHANGES_REQUESTED** [review]
- `L286` Check via dep_ch if ffpb is installed
- If it is, execute your code block
- If it isn't, execute the current code block
- Remove the pip install from the makefile

**Comment by ura43** [comment]
I'll soon™ work on a change to the README that enables seperate listing of optional dependencies with the feature they enable and add yours there

**Comment by ura43** [comment]
Fixed with #165 
Well, the progress indicator. It's not a bar, but gives you all the stats you want to know during download

**Pull request closed without merging**
