### PR TITLE
switched to vidcdn

### PR DESCRIPTION
**Pull request by CoolnsX**
@ura43  please check it...

### CODE REVIEW

**Review by ura43 — CHANGES_REQUESTED** [review]
Would it be hard to get rid of the jq requirement?

**Comment by CoolnsX** [comment]
> Would it be hard to get rid of the jq requirement?

yup... as it will make the scripting easier.. because hard coding everything is time consuming results in complexed script..

**Comment by ura43** [comment]
Currently discussing it with some users on the discord

**Comment by ura43** [comment]
But avoiding additional dependencies seems like a good default strategy

**Review by ura43 — APPROVED** [review]

**Pull request merged**
