### PR TITLE
qa: compliance with file system hierarchy

### PR DESCRIPTION
**Pull request by Derisis13**
# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [ ] Documentation update
- [x] Being picky

## Description

Potential fix for #773
Breaks self-updating again (this time I'll update the readme for sure, not gonna happen twice). Does this make it 4.0.0 or 3.2.0?

## Checklist

- [x] any anime playing
- [ ] bumped version
- [ ] next, prev and replay work
- [x] quality works
- [x] downloads work
- [x] quality works with downloads
- [ ] select episode -a and rapid resume work
- [ ] syncplay -s works
- [ ] autoplay, aka range selection, works

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Not uploaded: one piece dub episode 590
- Unreleased: soredemo ayumu wa yosetekuru
- Short id (for decryption): Log Horizon episode 1-2

### CODE REVIEW

**Comment by DaBigBlob** [comment]
yall do know that lib/ is supposed to contain libraries right?

**Comment by Derisis13** [comment]
> yall do know that lib/ is supposed to contain libraries right?

And what are the player and UI modules if not libraries? Binaries? Data? (Ofc it's data, everything is data in the Neumann architecture, but it isn't input nor output data)
They are libraries.

**Comment by tpeacock19** [comment]
`man file-hierarchy`

> VENDOR-SUPPLIED OPERATING SYSTEM RESOURCES
> /usr/lib/
> Static, private vendor data that is compatible with all architectures (though not necessarily architecture-independent). Note that this includes internal executables or other binaries that are not regularly invoked from a shell. Such binaries may be for any architecture supported by the system. Do not place public libraries in this directory, use $libdir (see below), instead.

> SYSTEM PACKAGES
>       Developers of system packages should follow strict rules when
       placing their files in the file system. The following table lists
       recommended locations for specific types of files supplied by the
       vendor.
>
>       Table 1. System package vendor files locations
> 
>       │/usr/lib/package/         │ Private static vendor    │
>       │                          │ resources of the         │
>       │                          │ package, including       │
>       │                          │ private binaries and     │
>       │                          │ libraries, or any other  │
>       │                          │ kind of read-only vendor │
>       │                          │ data.                    │

**Comment by Derisis13** [comment]
I get it now...
Making a dedicated subfolder would also make the upgrade procedure more robust; it makes a lot of sense. Thanks for sharing!

**Review by CoolnsX — APPROVED** [review]

**Pull request merged**
