### PR TITLE
Updated get_links and fixed get_video_quality function

### PR DESCRIPTION
**Pull request by RaynardGerraldo**
Video quality selecting now working again with the new updates

### CODE REVIEW

**Comment by ura43** [comment]
I'll take a look. Can you  review my open PR in the meantime?

**Review by ura43 — APPROVED** [review]
Can confirm working

**Comment by RaynardGerraldo** [comment]
> I'll take a look. ~Can you review my open PR in the meantime?~

sorry wasnt here, was it the README? looks good and thanks for the credit part, but i think the @MyName doesnt actually mention me

**Comment by ura43** [comment]
Oh true, because its in a quote. 
That section will be updated regularly to reflect some of the latest improvements.
I'll merge your PR

**Comment by ura43** [comment]
I asked pystardust to add you as a collaborator. 
If he does, would you be fine with me adding you to the readme as developer?
Formatwise it would be like the maintainer badge, but reading developer instead

**Comment by ura43** [comment]
Actually, calling you maintainer too wouldn't be an issue.
I'll give you whatever title you prefer

**Comment by RaynardGerraldo** [comment]
> I asked pystardust to add you as a collaborator. If he does, would you be fine with me adding you to the readme as developer? Formatwise it would be like the maintainer badge, but reading developer instead

wow thanks ,yea maintainer is fine with me🙂

**Pull request merged**
