### PR TITLE
Create install.sh

### PR DESCRIPTION
**Pull request by nabeelshaikh7**
Install.sh

- [ X] Feature

## Description
Install Script for Distros based upon Debian

## Checklist

- [ X] downloads work

### CODE REVIEW

**Comment by port19x** [comment]
Don’t care + didn’t ask + cry about it + stay mad + get real + L + mald seethe cope harder + ho mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + repelled + get a life + ok + and? + cringe + touch grass + donowalled + not based + your a (insert stereotype) + not funny didn’t laugh + you “re” + grammar issues + go outside + get good + reported + ad hominem + GG! + ask deez + ez clap + straight cash + ratio agian + final ratio + problematic

**Comment by toxicduccinator** [comment]
💀

**Comment by iamchokerman** [comment]
+1

**Comment by Derisis13** [comment]
I'm working on a .deb package, see #697

**Pull request closed without merging**
