### PR TITLE
docs: add fastanime to homies

### PR DESCRIPTION
**Pull request by Benex254**
## Type of change

- [ ] Bug fix
- [ ] Feature
- [x] Documentation update

## Description
Adds [FastAnime](https://github.com/Benex254/FastAnime) to homies which is just a tool that aims to replicate the anime browser site experience in the terminal.

### CODE REVIEW

**Comment by port19x** [comment]
That is a pretty huge readme you got there, but decently structured at the same time.

Out of curiosity, what makes fastanime any faster than any of the other python based scrapers?

**Comment by Benex254** [comment]
Well initially the name was out of spite to some guy who called my cli slow. Though eventually I did actually make it fast. I have implemented lazy loading of all the commands and all requests to the provider are cached to reduce repeated requests to the providers servers.

**Review by port19x — APPROVED** [review]

**Review by port19x — CHANGES_REQUESTED** [review]
oh no, your editor formatted a bunch of other stuff

**Comment by Benex254** [comment]
> oh no, your editor formatted a bunch of other stuff

I fixed this. It now only edits the homies section

**Review by port19x — APPROVED** [review]

**Comment by port19x** [comment]
Alright, welcome to the cool kids club

**Pull request merged**
