### PR TITLE
fix: new encryption keys & update encrypt url

### PR DESCRIPTION
**Pull request by brahmkshatriya**

### CODE REVIEW

**Review by port19x — APPROVED** [review]

**Comment by port19x** [comment]
a good message for the merge commit: `fix: new encryption keys(#644)`
waiting for one or two confirmations that it works again.
Will test it myself once I'm home in 1-2 hours max

**Comment by brahmkshatriya** [comment]
oh we aint doing caps?

**Comment by port19x** [comment]
why was this pr closed?

**Comment by port19x** [comment]
Oh whatever I'll just merge

**Comment by brahmkshatriya** [comment]
Lmao, I didnt test tho

**Comment by port19x** [comment]
Surely you tested the keys somewhere with something.
Such a small diff doesn't require full testing if thats what you meant

**Comment by port19x** [comment]
:eyes: you did, right?

**Comment by port19x** [comment]
Anyway, just confirmed working myself. Thank you for the fix

**Comment by brahmkshatriya** [comment]
> 👀 you did, right?

Yea confirmed on saikou :troll:

**Comment by rakusan2** [comment]
F It changed again a few minutes ago

**Pull request merged**
