### PR TITLE
fix: allanime scraping

### PR DESCRIPTION
**Pull request by justchokingaround**
# Pull Request Template

## Type of change

- [x] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

*ramble here*

## Checklist

- [x] any anime playing
- [x] bumped version
---
- [x] next, prev and replay work
- [x] `-c` history and continue work
- [x] `-d` downloads work
- [x] `-s` syncplay works
- [x] `-q` quality works
- [x] `-v` vlc works
- [x] `-e` select episode works
- [x] `-S` select index works
- [x] `-r` range selection works
- [x] `--dub` and regular (sub) mode both work
- [x] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [ ] `-h` help info is up to date
- [ ] Readme is up to date
- [ ] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

### CODE REVIEW

**Review by Lucifer25x — APPROVED** [review]
Works just fine

**Comment by justchokingaround** [comment]
TODOS:

- [ ] make quality work or remove that option
- [ ] scrape embeds as fallback if yt-hd and yt-sd links don't work

**Comment by port19x** [comment]
Basic functionality is working

**Comment by justchokingaround** [comment]
for testing fallback to embed:
```sh
ani-cli bungo stray dogs 4 -e 2
```

**Comment by justchokingaround** [comment]
should be gucci gang now

**Comment by 71zenith** [comment]
can confirm, works

**Comment by CaffeineB34r** [comment]
didn't work for me until i changed lines around 150 to `PF=`which printf`
    provider_id=$($PF "%b" "$hexadecimal_provider_id" | sed "s/\/clock/\/clock\.json/")`

**Review by nightwolf3140 — APPROVED** [review]
Haven't tested it myself, but should work.

**Review by 71zenith — APPROVED** [review]

**Review by port19x — APPROVED** [review]

**Pull request merged**
