### PR TITLE
Dead links check for wixmp

### PR DESCRIPTION
**Pull request by CoolnsX**
# Pull Request Template

## Type of change

- [x] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

Self Explainatory

## Checklist

- [X] any anime playing
- [x] bumped version
---
- [X] next, prev and replay work
- [X] `-c` history and continue work
- [X] `-d` downloads work
- [X] `-s` syncplay works
- [X] `-q` quality works
- [X] `-v` vlc works
- [X] `-e` select episode works
- [X] `-S` select index works
- [X] `-r` range selection works
- [X] `--dub` both work
- [X] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [ ] `-h` help info is up to date
- [ ] Readme is up to date
- [ ] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

### CODE REVIEW

**Review by 71zenith — APPROVED** [review]

**Review by port19x — CHANGES_REQUESTED** [review]
Doesn't this add one needless request?

**Comment by CoolnsX** [comment]
It does head request also wixmp links are not that common

**Comment by CoolnsX** [comment]
If u don't like it, I will remove it..

**Comment by port19x** [comment]
Its more that I don't see the value that is being added?
Don't we just ignore the potential empty return of a dead link anyway?
If we do, having a dead link check either
1. doesn't change total request latency, if all requests were sequential and the link is in fact dead
2. increments total request latency by the check latency, if all requests were sequential and the link is not dead
3. nearly doubles the request latency, assuming all other requests are concurrent

(total request latency being the time it takes to create the episode list)

Assuming my assumptions are correct, we should dismiss this change

**Pull request closed without merging**
