### PR TITLE
fix: no-detach detatching

### PR DESCRIPTION
**Pull request by port19x**
https://github.com/pystardust/ani-cli/pull/1264#issuecomment-1925810856

### CODE REVIEW

**Comment by port19x** [comment]
I think shellcheck is a little confused here

**Comment by germaniuss** [comment]
Just tested out this MR and it does not seem to work. I feel like not redirecting the mpv output to /dev/null is necessary since when used with the kitty protocol the frames are sent through a bytestream from mpv to the terminal.

**Comment by germaniuss** [comment]
> Just tested out this MR and it does not seem to work. I feel like not redirecting the mpv output to /dev/null is necessary since when used with the kitty protocol the frames are sent through a bytestream from mpv to the terminal.

By not work, I mean that the video is not showing. I no longer need to pkill the mpv process since it does not detach anymore, but the kitty protocol messages are not redirected to the terminal.

**Comment by port19x** [comment]
fixed, please try again to verify

**Comment by germaniuss** [comment]
Well that was fast haha, it does work now!!

**Comment by port19x** [comment]
On vacation doing some random coding currently :D

**Review by Derisis13 — APPROVED** [review]
So far so good. Shouldn't shellcheck catch this one?

**Comment by Derisis13** [comment]
oh wait, it did

**Comment by port19x** [comment]
Yeah, I wanted to be smart, but shellcheck didn't let me

**Pull request merged**
