### PR TITLE
Allow the user to choose his player

### PR DESCRIPTION
**Pull request by TheCactusVert**
- Allow the user to choose his player.
- Adding Celluloid as allowed player.

### CODE REVIEW

**Comment by ura43** [comment]
@RaynardGerraldo is already working with @tennyson-mccalla on implementing this.
If you want to review their implementation, check out #256

**Comment by django85** [comment]
This would be great.
E.g. I'm running OSMC and using the kodi-send command to play the video in ani-cli:
kodi-send --action="PlayMedia($play_link)"

A generic solution by using a config.ini file would be neat, something like this (in case of kodi):

[player]
cmd=kodi-send
param_string=--action="PlayMedia($play_link)"

**Comment by ura43** [comment]
We 100% won't use a config file @django85

**Comment by RaynardGerraldo** [comment]
> This would be great. E.g. I'm running OSMC and using the kodi-send command to play the video in ani-cli: kodi-send --action="PlayMedia($play_link)"
> 
> A generic solution by using a config.ini file would be neat, something like this (in case of kodi):
> 
> [player] cmd=kodi-send param_string=--action="PlayMedia($play_link)"

that would be too much of a hassle to implement, the plan for the support of multiple video players is basically match wildcard options and will only work with media player that can execute videos after its command, for ex: vlc <link>

**Pull request closed without merging**
