### PR TITLE
docs: spell check

### PR DESCRIPTION
**Pull request by Quicksilver151**
# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [x] Documentation update

## Description

*ramble here*

was bored

## Checklist

- [ ] any anime playing
- [ ] bumped version
---
- [ ] next, prev and replay work
- [ ] `-c` history and continue work
- [ ] `-d` downloads work
- [ ] `-s` syncplay works
- [ ] `-q` quality works
- [ ] `-v` vlc works
- [ ] `-e` select episode works
- [ ] `-S` select index works
- [ ] `-r` range selection works
- [ ] `--skip` ani-skip works
- [ ] `--skip-title` ani-skip title argument works
- [ ] `--no-detach` no detach works
- [ ] `--dub` and regular (sub) mode both work
- [ ] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [ ] `-h` help info is up to date
- [ ] Readme is up to date
- [ ] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

### CODE REVIEW

**Comment by port19x** [comment]
I like it. Did you check all the files?

**Comment by Quicksilver151** [comment]
i only modified two files

and it shouldnt effect any code. so not sure what you mean by check

btw not sure where to put this, but the link to allanime in the README.md needs to change

**Comment by port19x** [comment]
By check I meant spell check.
You can adapt the allanime link, we can do it in one PR.
Also adapt the allanime link in disclaimer.md while you're at it

**Comment by Quicksilver151** [comment]
yea i went through all the files. changed everyhing the lsp suggested

**Comment by Quicksilver151** [comment]
changed allanime references

**Review by port19x — APPROVED** [review]

**Pull request merged**
