### PR TITLE
Add Makefile for linux and change Readme a bit

### PR DESCRIPTION
**Pull request by Zay-Ta**

### CODE REVIEW

**Comment by 71zenith** [comment]
We make already told that make file will not be brought back. It creates more problem that it solves. 
Keeping it open for sometime if you have some doubts

**Comment by Zay-Ta** [comment]
yea i noticed that make file was removed from ani-cli but can u tell more about the problem it creates? I am just curious about it.

**Comment by ura43** [comment]
It was about 20% of the issues and easily 50% of the support requests.
Fundamentally changing the install process from the black box that is the makefile to clear instructions has made it easier to help people with exotic setups.
We also made a very sophisticated one, with platform detection and stuff. But that didn't solve the problem either.

Lastly, I believe copy pasting sudo make is no easier than copy pasting a sudo cp

**Comment by ura43** [comment]
For further context, read #417 or just search "makefile" in closed issues.

**Pull request closed without merging**
