### PR TITLE
small readme update

### PR DESCRIPTION
**Pull request by Spaxly**
title

### CODE REVIEW

**Comment by port19x** [comment]
:thinking:

**Comment by justchokingaround** [comment]
doesn't work on mac + not shell + ratio

**Comment by justchokingaround** [comment]
```sh
#!/bin/sh

base="https://ustvgo.tv/"
selection=$(curl -s "$base"|sed 's_<li>_\n_g'|sed -nE 's_.*a href="([^"]*)">([^<]*) <.*_\1\t\2_p'|
  fzf --with-nth 2.. --reverse --header "Select a channel to watch" --height=40% --border)
title=$(printf "%s" "$selection"|cut -f2)
url=$(printf "%s" "$selection"|cut -f1)
iframe=$(curl -s "$url"|sed -nE "s_.*iframe src='([^']*)'.*_\1_p")
hls_link=$(curl -s -e "$url" "$base$iframe"|sed -nE "s@.*hls_src='([^']*)'.*@\1@p")
[ -z "$hls_link" ] && echo "No HLS link found" && exit 1
mpv --force-media-title="$title" "$hls_link"
```
you can even write an alias for this, it's not hard to make it even shorter, i only made it more verbose so it's more understandable and readable

**Comment by port19x** [comment]
Yeah, it's an inferior lobster.
I'm still looking for a good reddit scraper if you're up to the challenge

**Comment by justchokingaround** [comment]
tv-cli is for live tv channels, not movies & tv shows. i just don't see why python would be necessary, it's very basic

**Comment by CoolnsX** [comment]
> Yeah, it's an inferior lobster. I'm still looking for a good reddit scraper if you're up to the challenge

added to my todo list

**Comment by Spaxly** [comment]
> tv-cli is for live tv channels, not movies & tv shows. i just don't see why python would be necessary, it's very basic

will rewrite ig

**Comment by Spaxly** [comment]
https://github.com/Spaxly/tv-cli

now in shell script.

**Comment by port19x** [comment]
Oh, if it's for live tv channels sure

**Review by port19x — APPROVED** [review]

**Pull request merged**
