### PR TITLE
docs: added FreeBSD installation instructions

### PR DESCRIPTION
**Pull request by ChromiumOS-Guy**
# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [x] Documentation update

## Description

I added Tier 2 FreeBSD support using the linuxemu (aka Linux ABI)
which is very simple to setup.

## Checklist

- [x] any anime playing
- [ ] bumped version
---
- [x] next, prev and replay work
- [x] `-c` history and continue work
- [x] `-d` downloads work
- [x] `-s` syncplay works
- [x] `-q` quality works
- [x] `-v` vlc works
- [x] `-e` select episode works
- [x] `-S` select index works
- [x] `-r` range selection works
- [x] `--skip` ani-skip works
- [x] `--skip-title` ani-skip title argument works
- [x] `--no-detach` no detach works
- [x] `--dub` and regular (sub) mode both work
- [x] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [x] `-h` help info is up to date
- [x] Readme is up to date
- [x] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

### CODE REVIEW

**Comment by ChromiumOS-Guy** [comment]
forgot to mention that ani-skip doesn't work on FreeBSD , should add that warning first

**Comment by 71zenith** [comment]
Does ani-cli not work without linuxemu on FreeBSD?
We aim to remain posix compatible therefore it should run on any unix system without any layer.

**Comment by 71zenith** [comment]
Am open to adding this to docs , but I would like to not have any more moving parts than necessary.

**Comment by ChromiumOS-Guy** [comment]
I am not near my pc right now but I'll check if it works without linux emu (by disabling it)

also its not modified it just works (except ani-skip which i need to investigate further)

if by moving parts you mean more OSs to support that I agree , though I did state in the docs it is not supported so you are committing to nothing long term so I hope that helps (I'll try to support it though).

**Comment by ChromiumOS-Guy** [comment]
also how does one enter debug mode on ani-cli because I didn't find any docs for it (though that's probably me being stupid)

**Comment by 71zenith** [comment]
By moving parts, i meant linuxemu being a middleman

**Comment by 71zenith** [comment]
> also how does one enter debug mode on ani-cli because I didn't find any docs for it (though that's probably me being stupid)

debug?
if u just want to print the links then
`ANI_CLI_PLAYER=debug ani-cli <args>`
if u want it to print all the commands being run then
`sh -x $(which ani-cli) <args>`

**Comment by 71zenith** [comment]
> I am not near my pc right now but I'll check if it works without linux emu (by disabling it)
> 
> also its not modified it just works (except ani-skip which i need to investigate further)
> 
> if by moving parts you mean more OSs to support that I agree , though I did state in the docs it is not supported so you are committing to nothing long term so I hope that helps (I'll try to support it though).

Fair, I've employed quite a number of hacks to get ani-skip working. Do report on what error ani-skip exits. Ill try to fix it.

**Comment by ChromiumOS-Guy** [comment]
Np, and thanksfor the help with the debug stuff, I'll get to it in ~1.5h when I'm home.

**Comment by ChromiumOS-Guy** [comment]
yeah turns out you don't need linux emu , so all is good on that part (removed it from docs)
I just assumed that from some reason even though it says in the docs its for unix based OSs 
which is just fun, sorry for the confusion.

**Comment by ChromiumOS-Guy** [comment]
well the debug stuff says all likes fetched which is nice, also I noticed this:

```sh
dropbox Links Fetched
sharepoint Links Fetched
sed: 1: "s|^#.*x||g; s|,.*|p|g;  ...": unterminated substitute pattern
gogoanime Links Fetched
```
it seems to have no effect on functionality (and frankly I have no Idea what you do with sed editor) but could this be why skip doesn't work ?
also here is the log relevant --skip:
```sh
$ ANI_CLI_PLAYER=debug ani-cli one piece --skip
Skip times not found!
```

**Comment by ChromiumOS-Guy** [comment]
forgot to say, yes --skip-title also works

**Comment by ChromiumOS-Guy** [comment]
so yeah everything works, no linuxemu required  If you pull I'll probably update this if something needs to be changes (which knowing FreeBSD probably means never or maybe maybe when FreeBSD 15 drops proper)

**Comment by justchokingaround** [comment]
please remove the part where each dependency is installed on its own, it's redundant

**Comment by ChromiumOS-Guy** [comment]
Sure!, done.
I just copied the style of the Steamdeck support but I don't mind at all.

**Review by justchokingaround — APPROVED** [review]

**Comment by justchokingaround** [comment]
great, thanks for your contribution!

**Pull request merged**
