### PR TITLE
some fixes

### PR DESCRIPTION
**Pull request by CoolnsX**
# Pull Request Template

## Type of change

- [x] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

*ramble here*

## Checklist

- [x] any anime playing
- [x] bumped version
- [x] next, prev and replay work
- [x] quality works
- [x] downloads work
- [x] quality works with downloads
- [x] select episode -a and rapid resume work
- [x] syncplay -s works
- [x] autoplay, aka range selection, works

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Not uploaded: one piece dub episode 590
- Unreleased: soredemo ayumu wa yosetekuru
- Short id (for decryption): Log Horizon episode 1-2

### CODE REVIEW

**Review by justchokingaround — APPROVED** [review]

**Review by port19x — APPROVED** [review]

**Comment by port19x** [comment]
What does this do? I don't wanna merge to master with "some fixes"

**Comment by Derisis13** [comment]
It fixes the issue of some episodes not loading by updating quality parser regexes and the gogoanime base url (it really should just be a variable though)

**Review by Derisis13 — CHANGES_REQUESTED** [review]
Can you extract the url `https://gogohd.net/` into a variable for ease of further maintenance and the possibility to automatically fetch it (either via following redirections or via regex parsing) in the future, if it becomes necessary?

**Comment by justchokingaround** [comment]
redirection + regex matching is a great idea

**Comment by port19x** [comment]
an uninstall before the install is only necessary for 3.2 and 3.2.x users. My change reflects that and also removes the "new in v3" section, as v3 is out for a while now

**Pull request merged**
