### PR TITLE
Fix #482 and proper indentation

### LINKED ISSUE #482: Episode selection doesn't check for under-indexing
**Metadata (please complete the following information)**
Version: 1.6.4
OS: Pop!_OS 21.10
Shell: bash
Anime: not applicable

**Describe the bug**
When you input a number lower than the specified range into the episode selection prompt, it tries to open the episode, which fails.

**Steps To Reproduce**

1. Run `ani-cli`
2. Search for any anime (eg. re:zero)
3. Choose something bellow the minimum ep. number (eg. -512)

**Expected behaviour**
I should receive an episode out of range warning and a new input dialouge

**Screenshots (if applicable)**
image

**Additional context**

### PR DESCRIPTION
**Pull request by RaynardGerraldo**
Fix episode selection not checking for negative number/under indexing
Proper indentation in query,history,a and h case
Remove curl attempt and 404 checking on link without "-episode" in url since all gogoanime links are now using "-episode-<eps_number>"

### CODE REVIEW

**Comment by RaynardGerraldo** [comment]
@Derisis13 good?

**Comment by 71zenith** [comment]
Cannot found url after a wrong episode is selected and prompted to again enter

**Comment by 71zenith** [comment]
a and h still don't have proper indentation

**Comment by freezboltz** [comment]
> a and h still don't have proper indentation

latest commit [0f9c7fe](https://github.com/pystardust/ani-cli/pull/480/commits/0f9c7fef804485caf89ecba4f06ce7e8b21a2bf9) in #480 fix proper indentation

**Comment by TheGlockMisc** [comment]
> Fix episode selection not checking for negative number/under indexing Proper indentation in query,history,a and h case Remove curl attempt and 404 checking on link without "-episode" in url since all gogoanime links are now using "-episode-<eps_number>"

Saekano [Saenai Heroine no Sodatekata ♭ ] still using non "-episode" prefix. theres another one but i forgot what anime.
Episode 1: https://www1.gogoanime.pe/saenai-heroine-no-sodatekata-2-1

But i dont think it is a large issue because most of the anime indexed with "-episode"

**Pull request closed without merging**
