### PR TITLE
Add packaging status section to readme

### PR DESCRIPTION
**Pull request by WillPower3309**
# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [x] Documentation update

## Description

I've been maintaining the ani-cli NUR (nix user repository) packaged ani-cli for a little while now, since noticing that a section in the readme exists for installation instructions, I'm offering up this update to the readme in case the maintainers are interested in mentioning its availability on Nix.

### CODE REVIEW

**Comment by WillPower3309** [comment]
Clarification on why it's formatted as is: in nix / nixos, since a system is typically managed via a file, the `nur.repos.willpower3309.ani-cli` text would be what is added to the packages list in a user's NUR enabled configuration. This would be apparent to a nix user but I realize may seem strange to potential reviewers :)

**Review by Derisis13 — DISMISSED** [review]
I looked into the repo and it looks OK, however I'd like to see exact installation instructions instead of the information that it's available. 
I want it to be as verbose as the other package installations: see the AUR and MacOS instructions for reference.

**Comment by port19x** [comment]
> Clarification on why it's formatted as is: in nix / nixos, since a system is typically managed via a file, the `nur.repos.willpower3309.ani-cli` text would be what is added to the packages list in a user's NUR enabled configuration. This would be apparent to a nix user but I realize may seem strange to potential reviewers :)

I've been eyeballing nix for a while, never getting brave enough to seriously hop to it.
I love the idea of maintaining system configuration in a git trackable file alongside the dotfiles, but since nix goes way beyond that and does many things very differently, my knowledge wouldn't cary over to daily IT operations at my day job.
Thanks for making the package.

Not sure how verbosely it needs to be documented, but I think derisis has a point

**Comment by port19x** [comment]
Alternatively, we could add the repology badge somewhere there

[Packaging status](https://repology.org/project/ani-cli/versions)

**Comment by Derisis13** [comment]
> Clarification on why it's formatted as is: in nix / nixos, since a system is typically managed via a file, the `nur.repos.willpower3309.ani-cli` text would be what is added to the packages list in a user's NUR enabled configuration. This would be apparent to a nix user but I realize may seem strange to potential reviewers :)

Oops, should have read it more thorougly. I still want to see at least which file it should be appended to, plus the install command (with whatever nix's package management is done). Not because it's not trivial, but because it's more convenient and it's understandable outside of the nix userbase (and even idiots won't try it).

**Comment by iamchokerman** [comment]
> Alternatively, we could add the repology badge somewhere there
> 
> [Packaging status](https://repology.org/project/ani-cli/versions)

i like this idea

**Comment by WillPower3309** [comment]
> > Clarification on why it's formatted as is: in nix / nixos, since a system is typically managed via a file, the `nur.repos.willpower3309.ani-cli` text would be what is added to the packages list in a user's NUR enabled configuration. This would be apparent to a nix user but I realize may seem strange to potential reviewers :)
> 
> Oops, should have read it more thorougly. I still want to see at least which file it should be appended to, plus the install command (with whatever nix's package management is done). Not because it's not trivial, but because it's more convenient and it's understandable outside of the nix userbase (and even idiots won't try it).

Absolutely! One thing that will need to be kept in mind for nix is that its structure doesn't allow for the update command to be used. Right now it prints an adequate message explaining why:

```
❯ ani-cli -U
File /nix/store/vrnjwn4zlgw1cq991rki9mnn7cwpvy7k-ani-cli/bin/.ani-cli-wrapped is read-only; trying to patch anyway
patch: **** Can't create temporary file /nix/store/vrnjwn4zlgw1cq991rki9mnn7cwpvy7k-ani-cli/bin/.ani-cli-wrapped.oKSSIZf : Read-only file system
Script has been updated
```

I'll submit a PR at some point to change it so it doesn't print the `Script has been updated` line since it's misleading.

The takeaway here though is that releases will have to be made for changes that fix ani-cli in the event that it breaks, as the `-U` flag will not work on nixOS / GuixSD.

**Comment by port19x** [comment]
> > > Clarification on why it's formatted as is: in nix / nixos, since a system is typically managed via a file, the `nur.repos.willpower3309.ani-cli` text would be what is added to the packages list in a user's NUR enabled configuration. This would be apparent to a nix user but I realize may seem strange to potential reviewers :)
> > 
> > 
> > Oops, should have read it more thorougly. I still want to see at least which file it should be appended to, plus the install command (with whatever nix's package management is done). Not because it's not trivial, but because it's more convenient and it's understandable outside of the nix userbase (and even idiots won't try it).
> 
> Absolutely! One thing that will need to be kept in mind for nix is that its structure doesn't allow for the update command to be used. Right now it prints an adequate message explaining why:
> 
> ```
> ❯ ani-cli -U
> File /nix/store/vrnjwn4zlgw1cq991rki9mnn7cwpvy7k-ani-cli/bin/.ani-cli-wrapped is read-only; trying to patch anyway
> patch: **** Can't create temporary file /nix/store/vrnjwn4zlgw1cq991rki9mnn7cwpvy7k-ani-cli/bin/.ani-cli-wrapped.oKSSIZf : Read-only file system
> Script has been updated
> ```
> 
> I'll submit a PR at some point to change it so it doesn't print the `Script has been updated` line since it's misleading.
> 
> The takeaway here though is that releases will have to be made for changes that fix ani-cli in the event that it breaks, as the `-U` flag will not work on nixOS / GuixSD. This is probably already done but worth mentioning so that you maintainers know how it differs on nix ;)

We typically do that, tho the cryptography frenzy in april was an exception.
Good to know that nixos and guix don't have the luxury of circumventing their package manager with -U, but I'm aware they get other great benefits

**Comment by iamchokerman** [comment]
looks good to me, however i'd like to know your thoughts on adding a short explanation of the difference between ani-cli and ani-cli-git for the aur package, since some people seem to not understand it

**Comment by port19x** [comment]
> looks good to me, however i'd like to know your thoughts on adding a short explanation of the difference between ani-cli and ani-cli-git for the aur package, since some people seem to not understand it

If you find some good way to say that ani-cli-git is proper rolling release and ani-cli isn't, sure.
Since this is a documentation update and #700 doesn't contain it yet, maybe you could add the revolt and matrix invites?

**Comment by iamchokerman** [comment]
> > looks good to me, however i'd like to know your thoughts on adding a short explanation of the difference between ani-cli and ani-cli-git for the aur package, since some people seem to not understand it
> 
> If you find some good way to say that ani-cli-git is proper rolling release and ani-cli isn't, sure. Since this is a documentation update and #700 doesn't contain it yet, maybe you could add the revolt and matrix invites?

yessir, however i couldn't find any cool embeds or svg so ig i'll just have to add an image with an href or smtg along those lines; might do some graphic design tonight to make some custom shit :pepebased:

**Comment by port19x** [comment]
> > > looks good to me, however i'd like to know your thoughts on adding a short explanation of the difference between ani-cli and ani-cli-git for the aur package, since some people seem to not understand it
> > 
> > 
> > If you find some good way to say that ani-cli-git is proper rolling release and ani-cli isn't, sure. Since this is a documentation update and #700 doesn't contain it yet, maybe you could add the revolt and matrix invites?
> 
> yessir, however i couldn't find any cool embeds or svg so ig i'll just have to add an image with an href or smtg along those lines; might do some graphic design tonight to make some custom shit :pepebased:

That would indeed be highly based

**Comment by WillPower3309** [comment]
Worth noting that the NUR package won't be able to be added to the repology status widget until https://github.com/repology/repology-updater/issues/872 is reopened + addressed.

**Comment by WillPower3309** [comment]
Should be in acceptable order now, should I update the PR title to include adding the repology packaging status?

**Comment by WillPower3309** [comment]
Wow I hadn't realized that ani-cli is actually available in nixpkgs unstable now! I'll remove my NUR portion of the readme since the official package would be preferred and is encompassed in the repology badge

**Comment by port19x** [comment]
> Wow I hadn't realized that ani-cli is actually available in nixpkgs unstable now! I'll remove my NUR portion of the readme since the official package would be preferred and is encompassed in the repology badge

The Nixos userbase might be the only competition to arch when it comes to availability of packages I care about

**Review by port19x — APPROVED** [review]

**Pull request merged**
