### PR TITLE
added so you can select all episodes when you select a range

### PR DESCRIPTION
**Pull request by BAaboe**
if you specify the range: 1 -1 it will automatically set the last ep in the range to the last ep in the anime

### CODE REVIEW

**Comment by freezboltz** [comment]
Suggestion:
anime like one piece, we have 1000+ ep
add some termination mechanism for script
otherwise it will be annoying

**Review by freezboltz — COMMENTED** [review]
for shell check use dash shell

**Review by ura43 — CHANGES_REQUESTED** [review]
- [ ] Bump to version 1.6.1
- [ ] Document the feature in the help string
- [ ] Document the feature in the readme

**Comment by BAaboe** [comment]
@ura43 it's fixed

**Review by ura43 — APPROVED** [review]

**Pull request merged**
