### PR TITLE
V2

### PR DESCRIPTION
**Pull request by ura43**
draft for now.
iirc we're only missing the new ui now

### CODE REVIEW

**Comment by ura43** [comment]
- [ ] any anime playing

**Comment by ura43** [comment]
- [ ] any anime playing
- [ ] all testcases playing
- [ ] next, prev and replay work
- [ ] quality works
- [ ] quality works with downloads
- [ ] download works
- [ ] select first and rapid resume work
- [ ] autoplay, aka range selection, works
- [ ] no shellcheck complaints
- [ ] reenable 2059 and disable it for the one line that purposefully ignores it
- [ ] update contributing.md
- [ ] update readme

**Comment by Derisis13** [comment]
awk is not being checked as a dependency btw

**Comment by ura43** [comment]
2022-04-01-135457_1534x753_scrot

Just a heads up that we have this aesthetic bug when having an old histfile / mixed histfile.
I know there is a converter script / there is supposed to be one

**Comment by CoolnsX** [comment]
> 2022-04-01-135457_1534x753_scrot
> 
> Just a heads up that we have this aesthetic bug when having an old histfile / mixed histfile. I know there is a converter script / there is supposed to be one

I know this bug which can be fixed.. while also increasing LOC.. which only shows when old histfile is parsed... So after switching to new histfile.. this bug will not show..

**Comment by ura43** [comment]
- [ ] Select first search result by default
- [ ] History conversion
- [ ] New testcase for unreleased anime
- [ ] Remove old anime and ep 5.5 testcase
- [ ] Document formal testing procedure

**Comment by ura43** [comment]
> > 2022-04-01-135457_1534x753_scrot
> > Just a heads up that we have this aesthetic bug when having an old histfile / mixed histfile. I know there is a converter script / there is supposed to be one
> 
> I know this bug which can be fixed.. while also increasing LOC.. which only shows when old histfile is parsed... So after switching to new histfile.. this bug will not be there..

I'd be okay with just telling our users to backing up their old histfile and start a fresh one

**Comment by CoolnsX** [comment]
> > > 2022-04-01-135457_1534x753_scrot
> > > Just a heads up that we have this aesthetic bug when having an old histfile / mixed histfile. I know there is a converter script / there is supposed to be one
> > 
> > 
> > I know this bug which can be fixed.. while also increasing LOC.. which only shows when old histfile is parsed... So after switching to new histfile.. this bug will not be there..
> 
> I'd be okay with just telling our users to back up their old histfile and start a fresh one

Put a disclaimer of two things:-
1. Please update ur script.. if u see sed warnings when running the script in ```ani-cli -c```
2. if u encounter "Video url not found", then make sure u are on latest version by typing ```ani-cli -U``` to update... Most of the time it's the older version that shows that message.. if after that u get the "No url found" then open a PR..

**Review by ura43 — COMMENTED** [review]
Can't approve the PR I opened :/

**Review by CoolnsX — APPROVED** [review]

**Comment by ura43** [comment]
roadmap

I propose a removal of the highlighted options from the interactive menu, as they have respective flags and aren't really useful to have interactively.
I see `(a) search` as an edge cases that seems to least unlikely to be useful

**Comment by ura43** [comment]
length

I'd also like a shorter alternative to `(episode n)` for length preview.
Since the main usecase appears to be visually filtering out movies, maybe a stylized M or TV could indicate the format.
Maybe a `(len x)`? 
I personally prefer less information in the anime selection menu

**Review by 71zenith — APPROVED** [review]

**Review by iamchokerman — APPROVED** [review]

**Pull request merged**
