### PR TITLE
Fix regex bug for gogoplay1 link

### PR DESCRIPTION
**Pull request by RaynardGerraldo**
Just tested the script a bunch of times and found a regex bug, updated error messages for both vlc and mpv using status code

### CODE REVIEW

**Review by ura43 — CHANGES_REQUESTED** [review]
This definitely enhances error handling.
But I don't believe your fix on line 261 to achieve anything, as it just narrows what passes the regex, maybe you can explain

**Comment by ura43** [comment]
Can't confirm fully functional. Still can't watch flcl progressive, but getting the error message from curl along the lines of "url not found" is a welcome improvement.
Option 1) You rename this PR to exclude "Fix regex bug for gogoplay1 link" and we merge just the error handling improvements
Option 2) You deepdive into the regex

**Comment by RaynardGerraldo** [comment]
> This definitely enhances error handling. But I don't believe your fix on line 261 to achieve anything, as it just narrows what passes the regex, maybe you can explain

ok so yesterday, i was testing the script with one piece episodes, and i noticed that curl was returning no url specified, tracked down the problem and it turned out to be the gogoplay link, so the previous regex "id.+?(=&)" matches the string id=ABCDEFGH=& , this was i think because i faced a link with an ID link this (a "=" sign before "&"), but the one piece link had this id=MTc2NjEx& which did not match with the regex, so i removed the "=" sign from regex "id.+?&" and now it matches both

**Comment by RaynardGerraldo** [comment]
> flcl progressive
 
looks like we got a new problem, turns out video links are not only from vidstreamingcdn, for animes like flcl progressive, it uses lb.loadfast1

**Comment by RaynardGerraldo** [comment]
> Can't confirm fully functional. Still can't watch flcl progressive, but getting the error message from curl along the lines of "url not found" is a welcome improvement. Option 1) You rename this PR to exclude "Fix regex bug for gogoplay1 link" and we merge just the error handling improvements Option 2) You deepdive into the regex

@ura43  just fixed the bug in my end, tested it with both dr stone and flcl progressive, but i might need more direct video links to confirm that my regex match is working,

**Comment by ura43** [comment]
> > This definitely enhances error handling. But I don't believe your fix on line 261 to achieve anything, as it just narrows what passes the regex, maybe you can explain
> 
> ok so yesterday, i was testing the script with one piece episodes, and i noticed that curl was returning no url specified, tracked down the problem and it turned out to be the gogoplay link, so the previous regex "id.+?(=&)" matches the string id=ABCDEFGH=& , this was i think because i faced a link with this ID link (a "=" sign before "&"), but the one piece link had this id=MTc2NjEx& which did not match with the regex, so i removed the "=" sign from regex "id.+?&" and now it matches both

Thanks for the clarification, makes sense in that case

**Comment by ura43** [comment]
Can also confirm working with flcl progressive

**Comment by ura43** [comment]
Confirmed working for 5 other anime, I think its safe to assume you fixed the issue.
But I'll go through the reported not working anime in #202 to further verify

**Review by ura43 — APPROVED** [review]

**Comment by ura43** [comment]
Confirmed working with all reported problematic anime. Will merge soon

**Comment by RaynardGerraldo** [comment]
> Confirmed working with all reported problematic anime. Will merge soon


good to know, btw just noticed that the video quality function is not working for this code's current state, i set it to always play highest quality as default, if its necessary ill try to update the get_video_quality function to work with the new updates,

**Comment by ura43** [comment]
So launching `ani-cli -q worst` ignores prefference and just plays the highest quality?

**Comment by ura43** [comment]
I think we should merge and open another issue to rework the -q option, as I believe far fewer users will worry about too high bandwith use over not being able to watch

**Comment by RaynardGerraldo** [comment]
> So launching `ani-cli -q worst` ignores prefference and just plays the highest quality?

sorry to say but it doesnt even play the video, ill look into it,  i also see that i can cut down some unnecessary codes while fixing this because its related

**Comment by ura43** [comment]
Is there a rate limit we may have run into?

**Comment by ura43** [comment]
Because after testing the ~10 anime earlier it also failed to play for me, but now it plays again.

**Comment by RaynardGerraldo** [comment]
> Is there a rate limit we may have run into?

Potentially yes, as mentioned in 5a0261126682295387977509066f8a6f0ead30f3 theres an "Error 1101" which i think is a rate limit,thats also why i added status code to detect the error before playing the video

**Comment by ura43** [comment]
Seems like #135 is a good ticket to track this follow up issue

**Pull request merged**
