### PR TITLE
Previous/next episode menu works on keypresses

### PR DESCRIPTION
**Pull request by Lukasz825700516**
Selection of next/previous episodes that shows up when opening an video,
now works by pressing single keys, without requirement of pressing
enter key.

### CODE REVIEW

**Comment by pystardust** [comment]
This is a POSIX sh script, read with those flags is a bash extension

**Comment by GMAGD** [comment]
hi, i've create a version that works with VLC 💯

**Comment by pystardust** [comment]
this is a cool feature but I feel the defaults are cleaner. Since if you press the key on accident you have a chance to correct  yourself

**Comment by Lukasz825700516** [comment]
Then should this be an option that would turn on with some flag like `-k` (key presses)?

**Comment by pystardust** [comment]
sounds good :D

**Comment by ura43** [comment]
> This is a POSIX sh script, read with those flags is a bash extension

Thats why shellcheck will be a thing soon

**Review by ura43 — APPROVED** [review]
Genius idea, I doubt I'll use anything but -k once I merged it.
The conflicts are rather simple to resolve. Leave that to me

**Pull request merged**
