### PR TITLE
ani-cli termux

### PR DESCRIPTION
**Pull request by John-Russel**
I create fork of ani-cli that works in termux

https://user-images.githubusercontent.com/38305533/149655564-e2304758-24e2-4c7d-a182-79901ba025f7.mp4

### CODE REVIEW

**Comment by ura43** [comment]
Currently @CoolnsX is maintaining a fork supporting ani-cli. I'll leave it to him wether he wants termux support in ani-cli.
But this would definitely not be merged into the main branch, but would get a seperate branch

**Comment by CoolnsX** [comment]
> Okay you can add android (termux) branch...



> I create fork of ani-cli that works in termux
> 
>  record-20220116-180440.mp4

He did it without any external termux dependency.... Good job.. even my fork requires termux-api(both app and as a package) in termux.. for just showing downloading notification..

**Comment by John-Russel** [comment]
i have experience coding startActivity in java and search how to do it in shell

**Comment by CoolnsX** [comment]
> i created a barch termux-mpv sorry for close and open im learning github

don't worry.. I was like that 1 month ago..

**Pull request closed without merging**
